name: Deploy to Prod

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.18.0]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Deploy env vars
        run: |
          # Create .env file from github secrets
          cat > .env << EOF
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}
          ARCJET_KEY=${{ secrets.ARCJET_KEY }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_STARTER_PRICE_ID=${{ secrets.STRIPE_STARTER_PRICE_ID }}
          STRIPE_PRO_PRICE_ID=${{ secrets.STRIPE_PRO_PRICE_ID }}
          ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}
          ECKOKIT_AGENT_ID=${{ secrets.ECKOKIT_AGENT_ID }}
          EOF
      - run: bun run build
      - name: Change directory to project
        run: cd /home/sanjay/actions-runner/_work/eckokit/eckokit/
      - run: pm2 restart 0
